name: Budowa Asystent NK Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalacja Flet
        run: pip install flet

      - name: Budowanie APK
        # Komenda 'yes |' automatycznie akceptuje pobieranie SDK przez Fleta
        run: yes | flet build apk --project "Asystent_NK" --product "Org_NK"

      - name: Udostępnienie pliku APK
        uses: actions/upload-artifact@v4
        with:
          name: Asystent-NK-APK
          # Używamy gwiazdek, aby znaleźć APK niezależnie od nazwy pliku wyjściowego
          path: build/apk/**/*.apk